name: test

on: [push]

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup OAT
        uses: ./
        with:
          version: "0.20.4"

      - name: Create zone
        run: |
          Linker -v sample_zone

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup OAT
        uses: ./
        with:
          version: "0.20.4"

      - name: Create zone
        run: |
          Linker -v sample_zone
